security:
  firewalls:
    backend:
      pattern: ^/admin
      provider: usuarios
      anonymous: ~
      form_login:
        login_path: admin_login
        check_path: admin_login_check
      remember_me:
        key: andeankey
        lifetime: 3600
      logout:
        path: /admin/logout
        target: /admin
  access_control:
    - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/admin/*, roles: ROLE_ADMIN }
  providers:
    usuarios:
      entity: { class: Andean\BackendBundle\Entity\Usuario, property: usuario }
  encoders:
    Andean\BackendBundle\Entity\Usuario: { algorithm: sha512 }